### ISSUE TITLE
Project cleanup master issue

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos#145]
This issue tracks the discussion and what needs to be done regarding cleaning up the Patmos/T-CREST repositories and their code.

Please feel free to talk about any of the issues by commenting, and I'll keep the list below updated where needed. 
If you make issues elsewhere as part of this work, please don't forget to link to this issue.

Current issues are:

- [ ]  Finish the Patmos code port to Chisel 3 and beyond.
    - 132 files still use the compatibility layer of Chisel 3, allowing Chisel 2 code with the `Chisel._` import. This should all be eliminated
    - [x] script simple changes (E.g., Bool(true) -> true.B) @tjarker
    - [X] Change `Vec.fill` @schoeberl 
    - [X] Move to Chisel 3.5 @schoeberl 
    - [ ] Move to Scala 2.13
    - [ ] Chisel 3.6
    - [ ] Chisel 5
    - [ ] Chisel 6
    - @schoeberl is lead
- [ ]  Updated CI testing of patmos
    - #142 will enable co-simulation with `pasim`
    - [ ] Move to using GitHub actions for CI instead of the current nightly running on helena
    - @Emoun is lead
- [ ] All chisel tests using the deprecated `iotester` are commented out. Port them to working test framework.
  - @EhsanKhodadad is lead
- [ ] Most cmp devices are not ported to Chisel 3.
  - They compile, but give runtime errors
  - [ ] Better solution for interface (soc-com)?
  - [ ] Device-specific tests are mostly not automated, make them so. E.g. Argo, SSPM
  - @tjarker is lead
- [ ] The rewrite of argo in Chisel needs to be finished
  - [ ] Currently, each module is compiled into a Verilog file imported individually. Update this such that everything happens within Chisel seamlessly.
  - @lucapezza is lead
- [ ] Finish the compiler update to new versions of LLVM.
  - [ ] Currently, the bootloader is likely being compiled incorrectly, making it unable to download programs.
  - [ ] Does not compile on ARM Mac. Fix this.
  - @Emoun is lead
- [ ] Find a better solution for pins (multiple IOs).
  - @tjarker is lead
- [ ] Get S4NOC back.
  - @schoeberl is lead

**Comment by schoeberl** [comment]
Thank you for summarizing this! If you don't mind, I've updated it a bit. I did not know that anyone could edit the original issue request. Very nice!

**Comment by schoeberl** [comment]
If you do changes related to Chisel 3, please tag the commit message with `chisel3: your comment`

**Comment by Emoun** [comment]
Just committed a fix to the patmos repository llvm2 branch that fixed the linker script, meaning we can now use the new compiler to download programs to an FPGA. Anyone interested should try this so we get it tested some more.
